/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.tchip.autosetting;

public final class R {
    public static final class anim {
        public static final int zms_translate_down_in=0x7f040000;
        public static final int zms_translate_down_out=0x7f040001;
        public static final int zms_translate_left_in=0x7f040002;
        public static final int zms_translate_left_out=0x7f040003;
        public static final int zms_translate_right_in=0x7f040004;
        public static final int zms_translate_right_out=0x7f040005;
        public static final int zms_translate_up_in=0x7f040006;
        public static final int zms_translate_up_out=0x7f040007;
        public static final int zoom_enter=0x7f040008;
        public static final int zoom_exit=0x7f040009;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int blue_dark=0x7f070000;
        public static final int blue_light=0x7f070001;
        public static final int content_color=0x7f070002;
        public static final int display_item_text_color=0x7f070003;
        public static final int display_time_text_color=0x7f070004;
        public static final int gravity_hint_main=0x7f070005;
        public static final int gravity_hint_vice=0x7f070006;
        public static final int gravity_level_text_color=0x7f070007;
        public static final int list_backgroud_color=0x7f070008;
        public static final int magic_btn_text_color=0x7f070009;
        public static final int quick_setting_text_color=0x7f07000a;
        public static final int setting_bg_color=0x7f07000b;
        public static final int setting_item_bg_grey=0x7f07000c;
        public static final int setting_item_separator=0x7f07000d;
        public static final int setting_item_title_color=0x7f07000e;
        public static final int setting_tab_bg=0x7f07000f;
        public static final int setting_tab_off=0x7f070010;
        public static final int setting_tab_on=0x7f070011;
        public static final int setting_tab_text_off=0x7f070012;
        public static final int setting_tab_text_on=0x7f070013;
        public static final int setting_title_bg=0x7f070014;
        public static final int title_color=0x7f070015;
        public static final int ui_back_arrow_bg_black_normal=0x7f070016;
        public static final int ui_back_arrow_bg_black_pressed=0x7f070017;
        public static final int ui_back_arrow_bg_blue_normal=0x7f070018;
        public static final int ui_back_arrow_bg_blue_pressed=0x7f070019;
        public static final int ui_back_arrow_bg_grey_normal=0x7f07001a;
        public static final int ui_back_arrow_bg_grey_pressed=0x7f07001b;
        public static final int ui_back_arrow_bg_transparent_normal=0x7f07001c;
        public static final int ui_back_arrow_bg_transparent_pressed=0x7f07001d;
        public static final int volume_bg=0x7f07001e;
        public static final int white=0x7f07001f;
    }
    public static final class dimen {
        public static final int gravity_hint_main_text_size=0x7f050000;
        public static final int gravity_hint_vice_text_size=0x7f050001;
        public static final int gravity_level_margin_left_right=0x7f050002;
        public static final int gravity_level_text_size=0x7f050003;
        public static final int gravity_seekbar_margin_left_right=0x7f050004;
        public static final int item_height=0x7f050005;
        public static final int item_icon_length=0x7f050006;
        public static final int item_icon_margin_left=0x7f050007;
        public static final int item_separator_height=0x7f050008;
        public static final int item_separator_margin=0x7f050009;
        public static final int item_switch_margin_right=0x7f05000a;
        public static final int item_title_margin_left=0x7f05000b;
        public static final int item_title_text_size=0x7f05000c;
        public static final int magic_btn_height=0x7f05000d;
        public static final int magic_btn_text_size=0x7f05000e;
        public static final int magic_btn_text_size_half=0x7f05000f;
        public static final int magic_btn_width=0x7f050010;
        public static final int magic_btn_width_half=0x7f050011;
        public static final int main_clock_text_size=0x7f050012;
        public static final int main_date_text_size=0x7f050013;
        public static final int main_title_text_size=0x7f050014;
        public static final int main_week_text_size=0x7f050015;
        public static final int quick_setting_bright_seekbar_margin_top=0x7f050016;
        public static final int quick_setting_icon_area_height=0x7f050017;
        public static final int quick_setting_icon_area_wdith=0x7f050018;
        public static final int quick_setting_icon_edge_length=0x7f050019;
        public static final int quick_setting_icon_margin=0x7f05001a;
        public static final int quick_setting_icon_margin_top=0x7f05001b;
        public static final int quick_setting_layout_switch_margin_left_right=0x7f05001c;
        public static final int quick_setting_layout_switch_margin_top=0x7f05001d;
        public static final int quick_setting_seekbar_icon_margin_left=0x7f05001e;
        public static final int quick_setting_text_margin_top=0x7f05001f;
        public static final int quick_setting_text_size=0x7f050020;
        public static final int quick_setting_total_height=0x7f050021;
        public static final int quick_setting_total_width=0x7f050022;
        public static final int quick_setting_volume_seekbar_margin_top=0x7f050023;
        public static final int setting_system_bright_item_height=0x7f050024;
        public static final int setting_system_bright_radio_margin=0x7f050025;
        public static final int setting_system_bright_text_size=0x7f050026;
        public static final int top_bar_height=0x7f050027;
        public static final int top_bar_title_margin_left=0x7f050028;
        public static final int ui_topbar_height=0x7f050029;
        public static final int volume_dialog_height=0x7f05002a;
        public static final int volume_dialog_margin=0x7f05002b;
        public static final int volume_dialog_width=0x7f05002c;
    }
    public static final class drawable {
        public static final int gravity_level_now_bg=0x7f020000;
        public static final int gravity_level_other_bg=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int icon_about=0x7f020003;
        public static final int icon_apn=0x7f020004;
        public static final int icon_crash=0x7f020005;
        public static final int icon_datausage=0x7f020006;
        public static final int icon_date=0x7f020007;
        public static final int icon_display=0x7f020008;
        public static final int icon_ota=0x7f020009;
        public static final int icon_park_monitor=0x7f02000a;
        public static final int icon_reset=0x7f02000b;
        public static final int icon_sound=0x7f02000c;
        public static final int icon_usb=0x7f02000d;
        public static final int icon_wifi=0x7f02000e;
        public static final int icon_wifi_ap=0x7f02000f;
        public static final int layout_backgroud=0x7f020022;
        public static final int line_background=0x7f020023;
        public static final int quick_setting_airplane_off=0x7f020010;
        public static final int quick_setting_airplane_on=0x7f020011;
        public static final int quick_setting_bg=0x7f020012;
        public static final int quick_setting_bluetooth_off=0x7f020013;
        public static final int quick_setting_bluetooth_on=0x7f020014;
        public static final int quick_setting_brightness=0x7f020015;
        public static final int quick_setting_brightness_auto=0x7f020016;
        public static final int quick_setting_data_off=0x7f020017;
        public static final int quick_setting_data_on=0x7f020018;
        public static final int quick_setting_gps_off=0x7f020019;
        public static final int quick_setting_gps_on=0x7f02001a;
        public static final int quick_setting_main_shortcut=0x7f02001b;
        public static final int quick_setting_volume=0x7f02001c;
        public static final int quick_setting_wifi_off=0x7f02001d;
        public static final int quick_setting_wifi_on=0x7f02001e;
        public static final int shape_quick_setting_bg=0x7f02001f;
        public static final int shape_setting_volume_bg=0x7f020020;
        public static final int ui_back_arrow_bg_transparent=0x7f020021;
    }
    public static final class id {
        public static final int backBitrate05=0x7f09002c;
        public static final int backBitrate1=0x7f09002d;
        public static final int backBitrate2=0x7f09002e;
        public static final int backBitrate3=0x7f09002f;
        public static final int backBitrate4=0x7f090030;
        public static final int backBitrateGroup=0x7f09002b;
        public static final int brightSeekBar=0x7f09005c;
        public static final int btnApplication=0x7f090014;
        public static final int btnCPUInfo=0x7f090011;
        public static final int btnCamera=0x7f090015;
        public static final int btnCloseCpuTemp=0x7f09001a;
        public static final int btnDeveloperSetting=0x7f090013;
        public static final int btnDeviceTest=0x7f09000d;
        public static final int btnEngineerMode=0x7f09000f;
        public static final int btnMtkLogger=0x7f090010;
        public static final int btnOpenCpuTemp=0x7f090019;
        public static final int btnOpenImageSensor=0x7f090016;
        public static final int btnSet=0x7f09001e;
        public static final int btnSystemSetting=0x7f09000e;
        public static final int frontBitrate10=0x7f090028;
        public static final int frontBitrate12=0x7f090029;
        public static final int frontBitrate6=0x7f090024;
        public static final int frontBitrate7=0x7f090025;
        public static final int frontBitrate8=0x7f090026;
        public static final int frontBitrate9=0x7f090027;
        public static final int frontBitrateGroup=0x7f090023;
        public static final int gravitySeekBar=0x7f090054;
        public static final int imageAirplane=0x7f09004a;
        public static final int imageBluetooth=0x7f090048;
        public static final int imageBrightness=0x7f09004c;
        public static final int imageData=0x7f090047;
        public static final int imageLocation=0x7f090049;
        public static final int imageSetting=0x7f090050;
        public static final int imageVolumeIcon=0x7f09004e;
        public static final int imageWifi=0x7f090046;
        public static final int itemAPN=0x7f090045;
        public static final int itemAbout=0x7f090044;
        public static final int itemCrash=0x7f09003d;
        public static final int itemDataUsage=0x7f09003b;
        public static final int itemDate=0x7f090041;
        public static final int itemDisplay=0x7f090036;
        public static final int itemOTA=0x7f090043;
        public static final int itemParkMonitor=0x7f09003e;
        public static final int itemReset=0x7f090042;
        public static final int itemSound=0x7f090037;
        public static final int itemStorage=0x7f09003c;
        public static final int itemUsb=0x7f090040;
        public static final int itemWifi=0x7f090038;
        public static final int itemWifiAp=0x7f09003a;
        public static final int layoutAutoLight=0x7f090058;
        public static final int layoutBright=0x7f09004b;
        public static final int layoutDate=0x7f090032;
        public static final int layoutMagic=0x7f09000b;
        public static final int layoutRecord=0x7f090020;
        public static final int layoutRow1=0x7f09000c;
        public static final int layoutRow2=0x7f090012;
        public static final int layoutRow3=0x7f090017;
        public static final int layoutSeekBar=0x7f09005a;
        public static final int layoutTop=0x7f090031;
        public static final int screenOff10min=0x7f090061;
        public static final int screenOff1min=0x7f09005f;
        public static final int screenOff2min=0x7f090060;
        public static final int screenOff30Second=0x7f09005e;
        public static final int screenOffGroup=0x7f09005d;
        public static final int screenOffNone=0x7f090062;
        public static final int seekBarBright=0x7f09004d;
        public static final int seekBarContrastDay=0x7f090006;
        public static final int seekBarContrastNight=0x7f090008;
        public static final int seekBarLightDay=0x7f090000;
        public static final int seekBarLightNight=0x7f090002;
        public static final int seekBarLightNight2=0x7f090004;
        public static final int seekBarVolume=0x7f09004f;
        public static final int switchAccOffWake=0x7f090018;
        public static final int switchAutolight=0x7f090059;
        public static final int switchFM=0x7f09001b;
        public static final int switchGravity=0x7f090051;
        public static final int switchParking=0x7f09003f;
        public static final int switchUVC=0x7f09001c;
        public static final int textBitrateBackTitle=0x7f09002a;
        public static final int textBitrateFrontTitle=0x7f090022;
        public static final int textClock=0x7f090035;
        public static final int textContrastDay=0x7f090007;
        public static final int textContrastNight=0x7f090009;
        public static final int textDate=0x7f090033;
        public static final int textHigh=0x7f090057;
        public static final int textHint=0x7f09001f;
        public static final int textHintMain=0x7f090052;
        public static final int textHintReboot=0x7f090021;
        public static final int textHintVice=0x7f090053;
        public static final int textInput=0x7f09001d;
        public static final int textLightDay=0x7f090001;
        public static final int textLightNight=0x7f090003;
        public static final int textLightNight2=0x7f090005;
        public static final int textLow=0x7f090055;
        public static final int textMiddle=0x7f090056;
        public static final int textPass=0x7f09000a;
        public static final int textTitleDisplay=0x7f09005b;
        public static final int textView1=0x7f090039;
        public static final int textWeek=0x7f090034;
        public static final int volumeMedia=0x7f090063;
        public static final int volumeRing=0x7f090064;
    }
    public static final class layout {
        public static final int activity_image_sensor_modify=0x7f030000;
        public static final int activity_magic=0x7f030001;
        public static final int activity_main=0x7f030002;
        public static final int activity_quick_setting=0x7f030003;
        public static final int activity_setting_gravity=0x7f030004;
        public static final int activity_setting_system_display=0x7f030005;
        public static final int activity_setting_system_volume=0x7f030006;
    }
    public static final class string {
        public static final int app_name=0x7f080000;
        public static final int display_auto_adjust=0x7f080001;
        public static final int display_auto_dim=0x7f080002;
        public static final int display_brightness=0x7f080003;
        public static final int display_time_10m=0x7f080004;
        public static final int display_time_1m=0x7f080005;
        public static final int display_time_2m=0x7f080006;
        public static final int display_time_30s=0x7f080007;
        public static final int display_time_forever=0x7f080008;
        public static final int gravity_hint_main=0x7f080009;
        public static final int gravity_hint_vice=0x7f08000a;
        public static final int gravity_level_high=0x7f08000b;
        public static final int gravity_level_low=0x7f08000c;
        public static final int gravity_level_middle=0x7f08000d;
        public static final int image_sensor_0_255=0x7f08000e;
        public static final int image_sensor_contrast_day=0x7f08000f;
        public static final int image_sensor_contrast_night=0x7f080010;
        public static final int image_sensor_light_day=0x7f080011;
        public static final int image_sensor_light_night=0x7f080012;
        public static final int image_sensor_light_night2=0x7f080013;
        public static final int image_sensor_saturation=0x7f080014;
        public static final int image_sensor_set=0x7f080015;
        public static final int magic_application=0x7f080016;
        public static final int magic_audio_set=0x7f080017;
        public static final int magic_back_off=0x7f080018;
        public static final int magic_back_on=0x7f080019;
        public static final int magic_back_record=0x7f08001a;
        public static final int magic_close_cpu_temp=0x7f08001b;
        public static final int magic_cpu_info=0x7f08001c;
        public static final int magic_developer_option=0x7f08001d;
        public static final int magic_device_test=0x7f08001e;
        public static final int magic_engineer_mode=0x7f08001f;
        public static final int magic_fm_off=0x7f080020;
        public static final int magic_fm_on=0x7f080021;
        public static final int magic_hint_input_pass=0x7f080022;
        public static final int magic_input_audio_channel=0x7f080023;
        public static final int magic_mtk_logger=0x7f080024;
        public static final int magic_open_cpu_temp=0x7f080025;
        public static final int magic_open_img_sensor=0x7f080026;
        public static final int magic_record_bitrate_05m=0x7f080027;
        public static final int magic_record_bitrate_10m=0x7f080028;
        public static final int magic_record_bitrate_12m=0x7f080029;
        public static final int magic_record_bitrate_1m=0x7f08002a;
        public static final int magic_record_bitrate_2m=0x7f08002b;
        public static final int magic_record_bitrate_3m=0x7f08002c;
        public static final int magic_record_bitrate_4m=0x7f08002d;
        public static final int magic_record_bitrate_6m=0x7f08002e;
        public static final int magic_record_bitrate_7m=0x7f08002f;
        public static final int magic_record_bitrate_8m=0x7f080030;
        public static final int magic_record_bitrate_9m=0x7f080031;
        public static final int magic_record_bitrate_back=0x7f080032;
        public static final int magic_record_bitrate_front=0x7f080033;
        public static final int magic_system_camera=0x7f080034;
        public static final int magic_system_setting=0x7f080035;
        public static final int magic_usb_mode=0x7f080036;
        public static final int magic_uvc_mode=0x7f080037;
        public static final int quick_setting_airplane_on=0x7f080038;
        public static final int quick_setting_text_airplane=0x7f080039;
        public static final int quick_setting_text_bluetooth=0x7f08003a;
        public static final int quick_setting_text_data=0x7f08003b;
        public static final int quick_setting_text_gps=0x7f08003c;
        public static final int quick_setting_text_wlan=0x7f08003d;
        public static final int set_success_reboot=0x7f08003e;
        public static final int text_hint=0x7f08003f;
        public static final int text_usb_mode=0x7f080040;
        public static final int title_about=0x7f080041;
        public static final int title_apn=0x7f080042;
        public static final int title_crash=0x7f080043;
        public static final int title_date_time=0x7f080044;
        public static final int title_display=0x7f080045;
        public static final int title_ota=0x7f080046;
        public static final int title_park_monitor=0x7f080047;
        public static final int title_reset=0x7f080048;
        public static final int title_setting=0x7f080049;
        public static final int title_setting_gravity=0x7f08004a;
        public static final int title_sound=0x7f08004b;
        public static final int title_storage=0x7f08004c;
        public static final int title_traffic_status=0x7f08004d;
        public static final int title_usb=0x7f08004e;
        public static final int title_wifi=0x7f08004f;
        public static final int title_wifi_ap=0x7f080050;
        public static final int volume_ringtone=0x7f080051;
    }
    public static final class style {
        /**  API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 
 API 21 theme customizations can go here. 

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.



        
         */
        public static final int AppBaseTheme=0x7f060002;
        public static final int AppTheme=0x7f060003;
        public static final int ThemeQuickSettingDialog=0x7f060000;
        public static final int ThemeVolumeDialog=0x7f060001;
    }
}
